name: CI

"on": ["pull_request", "push"]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2

      - uses: pre-commit/action@v2.0.3

  typing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # full history for setuptools_scm

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Python install
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run mypy
        run: tox -e typing

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # full history for setuptools_scm

      - name: Set up Python
        uses: actions/setup-python@v2

        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pandoc
        run: brew install pandoc

      - name: Python install
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox
        run: tox -e py,packaging
